In [58]:
import pandas as pd
df = pd.read_csv("steam.csv", encoding="latin-1")
df.head()

,types,name,all_reviews,release_date,developer,publisher,popular_tags,game_details,languages,genre,minimum_requirements,recommended_requirements,price
0,app,DOOM,"Very Positive,(42,550),- 92% of the 42,550 use...","May 12, 2016",id Software,"Bethesda Softworks,Bethesda Softworks","FPS,Gore,Action,Demons,Shooter,First-Person,Gr...","Single-player,Multi-player,Co-op,Steam Achieve...","English,French,Italian,German,Spanish - Spain,...",Action,"Minimum:,OS:,Windows 7/8.1/10 (64-bit versions...","Recommended:,OS:,Windows 7/8.1/10 (64-bit vers...",$19.99
1,app,PLAYERUNKNOWN'S BATTLEGROUNDS,"Mixed,(836,608),- 49% of the 836,608 user revi...","Dec 21, 2017",PUBG Corporation,"PUBG Corporation,PUBG Corporation","Survival,Shooter,Multiplayer,Battle Royale,PvP...","Multi-player,Online Multi-Player,Stats","English,Korean,Simplified Chinese,French,Germa...","Action,Adventure,Massively Multiplayer","Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$29.99
2,app,BATTLETECH,"Mostly Positive,(7,030),- 71% of the 7,030 use...","Apr 24, 2018",Harebrained Schemes,"Paradox Interactive,Paradox Interactive","Mechs,Strategy,Turn-Based,Turn-Based Tactics,S...","Single-player,Multi-player,Online Multi-Player...","English,French,German,Russian","Action,Adventure,Strategy","Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$39.99
3,app,DayZ,"Mixed,(167,115),- 61% of the 167,115 user revi...","Dec 13, 2018",Bohemia Interactive,"Bohemia Interactive,Bohemia Interactive","Survival,Zombies,Open World,Multiplayer,PvP,Ma...","Multi-player,Online Multi-Player,Steam Worksho...","English,French,Italian,German,Spanish - Spain,...","Action,Adventure,Massively Multiplayer","Minimum:,OS:,Windows 7/8.1 64-bit,Processor:,I...","Recommended:,OS:,Windows 10 64-bit,Processor:,...",$44.99
4,app,EVE Online,"Mostly Positive,(11,481),- 74% of the 11,481 u...","May 6, 2003",CCP,"CCP,CCP","Space,Massively Multiplayer,Sci-fi,Sandbox,MMO...","Multi-player,Online Multi-Player,MMO,Co-op,Onl...","English,German,Russian,French","Action,Free to Play,Massively Multiplayer,RPG,...","Minimum:,OS:,Windows 7,Processor:,Intel Dual C...","Recommended:,OS:,Windows 10,Processor:,Intel i...",Free

In [59]:
df.shape

(40833, 13)

In [60]:
df.isnull().sum()

types                           2
name                           16
all_reviews                 12363
release_date                 3179
developer                     343
publisher                    5100
popular_tags                 2945
game_details                  520
languages                      36
genre                         438
minimum_requirements        19764
recommended_requirements    19758
price                        5311
dtype: int64

In [61]:
for col in df.columns:
    if df[col].dtype=="object":
        df[col].fillna(df[col].mode()[0],inplace=True)
    elif (df[col].dtype in ["int64","float64"]) :
       df[col].fillna(0,inplace=True)
df.isnull().sum()

C:\Users\Naores\AppData\Local\Temp\ipykernel_15912\2488939538.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0],inplace=True)

types                       0
name                        0
all_reviews                 0
release_date                0
developer                   0
publisher                   0
popular_tags                0
game_details                0
languages                   0
genre                       0
minimum_requirements        0
recommended_requirements    0
price                       0
dtype: int64

In [62]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
40828     True
40829    False
40830    False
40831    False
40832    False
Length: 40833, dtype: bool

In [63]:
df=df.drop_duplicates()
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
40827    False
40829    False
40830    False
40831    False
40832    False
Length: 40709, dtype: bool

In [ ]:
df.dtypes

types                       object
name                        object
all_reviews                 object
release_date                object
developer                   object
publisher                   object
popular_tags                object
game_details                object
languages                   object
genre                       object
minimum_requirements        object
recommended_requirements    object
price                       object
dtype: object

In [ ]:
df["release_date"] = pd.to_datetime(df["release_date"], format="mixed", errors="coerce")

In [ ]:
df=df.rename(columns={"all_reviews":"reviews"})
df.columns

Index(['types', 'name', 'reviews', 'release_date', 'developer', 'publisher',
       'popular_tags', 'game_details', 'languages', 'genre',
       'minimum_requirements', 'recommended_requirements', 'price'],
      dtype='object')

In [ ]:
df["minimum_requirements"] = df["minimum_requirements"].str.split(",", n=1).str[1] #n=1 pour agir sur le premier : seulement
df["recommended_requirements"] = df["recommended_requirements"].str.split(",", n=1).str[1] #n=1 pour agir sur le premier : seulement
df["reviews"] = df["reviews"].str.split(",", n=1).str[0] 
df.head()

,types,name,reviews,release_date,developer,publisher,popular_tags,game_details,languages,genre,minimum_requirements,recommended_requirements,price
0,app,DOOM,Very Positive,2016-05-12,id Software,"Bethesda Softworks,Bethesda Softworks","FPS,Gore,Action,Demons,Shooter,First-Person,Gr...","Single-player,Multi-player,Co-op,Steam Achieve...","English,French,Italian,German,Spanish - Spain,...",Action,"OS:,Windows 7/8.1/10 (64-bit versions),Process...","OS:,Windows 7/8.1/10 (64-bit versions),Process...",$19.99
1,app,PLAYERUNKNOWN'S BATTLEGROUNDS,Mixed,2017-12-21,PUBG Corporation,"PUBG Corporation,PUBG Corporation","Survival,Shooter,Multiplayer,Battle Royale,PvP...","Multi-player,Online Multi-Player,Stats","English,Korean,Simplified Chinese,French,Germa...","Action,Adventure,Massively Multiplayer",Requires a 64-bit processor and operating syst...,Requires a 64-bit processor and operating syst...,$29.99
2,app,BATTLETECH,Mostly Positive,2018-04-24,Harebrained Schemes,"Paradox Interactive,Paradox Interactive","Mechs,Strategy,Turn-Based,Turn-Based Tactics,S...","Single-player,Multi-player,Online Multi-Player...","English,French,German,Russian","Action,Adventure,Strategy",Requires a 64-bit processor and operating syst...,Requires a 64-bit processor and operating syst...,$39.99
3,app,DayZ,Mixed,2018-12-13,Bohemia Interactive,"Bohemia Interactive,Bohemia Interactive","Survival,Zombies,Open World,Multiplayer,PvP,Ma...","Multi-player,Online Multi-Player,Steam Worksho...","English,French,Italian,German,Spanish - Spain,...","Action,Adventure,Massively Multiplayer","OS:,Windows 7/8.1 64-bit,Processor:,Intel Core...","OS:,Windows 10 64-bit,Processor:,Intel Core i5...",$44.99
4,app,EVE Online,Mostly Positive,2003-05-06,CCP,"CCP,CCP","Space,Massively Multiplayer,Sci-fi,Sandbox,MMO...","Multi-player,Online Multi-Player,MMO,Co-op,Onl...","English,German,Russian,French","Action,Free to Play,Massively Multiplayer,RPG,...","OS:,Windows 7,Processor:,Intel Dual Core @ 2.0...","OS:,Windows 10,Processor:,Intel i7-7700 or AMD...",Free